# latest verions
version: '3.7'
services:
  # api service
  api_server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: user-cms-api
    restart: always
    ports:
      - 3000:3000
  
  # frontend service
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: user-cms-frontend
    ports:
      - 8000:80
    depends_on:
      - api_server

